"""add language to posts

Revision ID: 985a764890c0
Revises: e61a8472917a
Create Date: 2024-08-28 00:39:36.820443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985a764890c0'
down_revision = 'e61a8472917a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
